//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WA_Blogers_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WA_BlogerEntities : DbContext
    {
        public WA_BlogerEntities()
            : base("name=WA_BlogerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WA_Blogs> WA_Blogs { get; set; }
        public virtual DbSet<WA_Comments> WA_Comments { get; set; }
        public virtual DbSet<WA_GroupUser> WA_GroupUser { get; set; }
        public virtual DbSet<WA_Likes> WA_Likes { get; set; }
        public virtual DbSet<WA_Options> WA_Options { get; set; }
        public virtual DbSet<WA_Posts> WA_Posts { get; set; }
        public virtual DbSet<WA_Roles> WA_Roles { get; set; }
        public virtual DbSet<WA_Users> WA_Users { get; set; }
    }
}
