//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WA_Blogers_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WA_Blogs
    {
        public WA_Blogs()
        {
            this.WA_Blogs1 = new HashSet<WA_Blogs>();
            this.WA_Posts = new HashSet<WA_Posts>();
        }
    
        public int BlogID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<int> Order { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<WA_Blogs> WA_Blogs1 { get; set; }
        public virtual WA_Blogs WA_Blogs2 { get; set; }
        public virtual ICollection<WA_Posts> WA_Posts { get; set; }
    }
}
