//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace WA_Blogers_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WA_Roles
    {
        public WA_Roles()
        {
            this.WA_GroupUser = new HashSet<WA_GroupUser>();
        }
    
        public int RoleID { get; set; }
        [Required]
        [Display(Name="Tên Quyền")]
        public string RoleName { get; set; }
        [Required]
        [Display(Name = "Mô Tả Quyền")]
        public string Description { get; set; }
    
        public virtual ICollection<WA_GroupUser> WA_GroupUser { get; set; }
    }
}
