//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WA_Blogers_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WA_Users
    {
        public WA_Users()
        {
            this.WA_Comments = new HashSet<WA_Comments>();
            this.WA_Likes = new HashSet<WA_Likes>();
            this.WA_Posts = new HashSet<WA_Posts>();
            this.WA_Roles = new HashSet<WA_Roles>();
        }
    
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Avatar { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string IPLast { get; set; }
        public string IPCreated { get; set; }
    
        public virtual ICollection<WA_Comments> WA_Comments { get; set; }
        public virtual ICollection<WA_Likes> WA_Likes { get; set; }
        public virtual ICollection<WA_Posts> WA_Posts { get; set; }
        public virtual ICollection<WA_Roles> WA_Roles { get; set; }
    }
}
